[package]
name = "KrKrTools"
version = "0.1.0"
edition = "2024"
authors = ["XuanRikka <xuanrikka@qq.com>"]
license = "MIT"

[[bin]]
name = "KrKrDescrambler-rs"
path = "src/KrKrDescrambler-rs/krkr_descrambler.rs"

[[bin]]
name = "KrKrScrambler-rs"
path = "src/KrKrDescrambler-rs/krkr_scrambler.rs"

[[bin]]
name = "XP3Pack"
path = "src/XP3Tools/xp3pack.rs"

[[bin]]
name = "XP3Unpack"
path = "src/XP3Tools/xp3Unpack.rs"

[profile.release]
opt-level = 3
lto = "fat"
inline-threshold = 114514
strip = true
overflow-checks = false

[dependencies]
binread = "2.2.0"
binwrite = "0.2.1"
clap = { version = "4.5.48", features = ["derive"] }
flate2 = "1.1.2"
scroll = "0.13.0"
walkdir = "2.5.0"
